sudo : required
services :
  - docker
before_install :
  - docker build -t adichamoli/dev_docker -f Dockerfile.dev .
  
script :
  - docker run -e CI=true adichamoli/dev_docker npm run test -- --coverage